#!/usr/bin/env python3

import argparse

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd

FIGSIZE = (5, 4)

REPLACEMENTS = {
    "bbr": "BBR",
    "cubic": "Cubic",
    "dctcp": "DCTCP",
    "disable": "disabled",
    "enable": "enabled",
    "gro": "GRO",
    "int": "INT",
    "reno": "Reno",
}


def main():
    plt.rcParams.update({"pdf.fonttype": 42})

    try:
        mpl.style.use("seaborn-v0_8-colorblind")
    except Exception as e:
        print("Failed to change matplotlib style: {}".format(e))

    argparser = argparse.ArgumentParser()
    argparser.add_argument(
        "--link-speed",
        default=25,
        type=int,
        help="speed of the measured link in Gbit/s",
    )
    argparser.add_argument("csv_file", type=argparse.FileType("r"))
    args = argparser.parse_args()

    df = pd.read_csv(args.csv_file).rename(columns=REPLACEMENTS).replace(REPLACEMENTS)
    args.csv_file.close()  # Be nice and close files :-)

    df["avg_throughput"] /= 10**9

    means = pd.pivot_table(df, columns=["GRO", "INT"], index="cca")

    fig, ax = plt.subplots(figsize=FIGSIZE, layout="constrained")
    ax = means["avg_throughput"].plot(
        ax=ax,
        kind="bar",
        rot=0,
        xlabel="Congestion control algorithm",
        ylabel="Avg. throughput (Gbps)",
    )
    ax.grid(linestyle="--")
    ax.set_ylim(0, args.link_speed)
    ax.yaxis.set_major_locator(ticker.FixedLocator([1, 10, 15, 20, 25, 50, 100]))
    fig.savefig("cca-gro-int-avg_throughput.pdf")
    plt.show()


if __name__ == "__main__":
    raise SystemExit(main())
