#!/usr/bin/env python3

import argparse

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd

REPLACEMENTS = {
    "bbr": "BBR",
    "cubic": "Cubic",
    "dctcp": "DCTCP",
    "disable": "disabled",
    "enable": "enabled",
    "gro": "GRO",
    "int": "INT",
    "reno": "Reno",
}


def main():
    argparser = argparse.ArgumentParser()
    argparser.add_argument("csv_file", type=argparse.FileType("r"))
    args = argparser.parse_args()

    df = pd.read_csv(args.csv_file).rename(columns=REPLACEMENTS).replace(REPLACEMENTS)
    args.csv_file.close()  # Be nice and close files :-)

    means = pd.pivot_table(df, columns=["GRO", "INT"], index="cca")
    errors = pd.pivot_table(df, aggfunc="std", columns=["GRO", "INT"], index="cca")

    fig, ax = plt.subplots(layout="constrained")
    ax = means["avg_throughput"].plot(
        ax=ax,
        capsize=3,
        kind="bar",
        rot=0,
        xlabel="Congestion control algorithm",
        yerr=errors["avg_throughput"],
        ylabel="Avg. throughput",
    )
    ax.yaxis.set_major_formatter(ticker.EngFormatter(unit="bit/s"))
    fig.savefig("cca-gro-int-avg_throughput.pdf")
    plt.show()


if __name__ == "__main__":
    raise SystemExit(main())
