#!/usr/bin/env python3

import argparse

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd


def main():
    argparser = argparse.ArgumentParser()
    argparser.add_argument("csv_file", type=argparse.FileType("r"))
    args = argparser.parse_args()

    df = pd.read_csv(args.csv_file)
    args.csv_file.close()  # Be nice and close files :-)

    means = pd.pivot_table(df, columns=["gro", "int"], index="cca")
    errors = pd.pivot_table(df, aggfunc="std", columns=["gro", "int"], index="cca")

    _fig, ax = plt.subplots(layout="constrained")
    ax = means["avg_throughput"].plot(
        ax=ax,
        capsize=3,
        kind="bar",
        xlabel="Congestion control algorithm",
        yerr=errors["avg_throughput"],
        ylabel="Avg. throughput",
    )
    ax.yaxis.set_major_formatter(ticker.EngFormatter(unit="bit/s"))
    plt.show()


if __name__ == "__main__":
    raise SystemExit(main())
