#!/usr/bin/env python3

import argparse

import matplotlib as mpl
import matplotlib.legend_handler
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd

FIGSIZE = (4, 3)

REPLACEMENTS = {
    "gro": "GRO",
    "int": "INT",
}


def main():
    plt.rcParams.update({"pdf.fonttype": 42})

    try:
        mpl.style.use("seaborn-v0_8-colorblind")
    except Exception as e:
        print("Failed to change matplotlib style: {}".format(e))

    argparser = argparse.ArgumentParser()
    argparser.add_argument("csv_file", type=argparse.FileType("r"))
    argparser.add_argument(
        "--max-iratio", type=int, help="maximum iratio value to plot"
    )
    args = argparser.parse_args()

    df = pd.read_csv(args.csv_file).rename(columns=REPLACEMENTS).replace(REPLACEMENTS)
    args.csv_file.close()  # Be nice and close files :-)

    if df["cca"].nunique() > 1:
        return "cannot plot for multiple CCAs"
    cca = df.loc[0, "cca"]

    max_iratio = max(df["iratio"])
    try:
        max_iratio = min(args.max_iratio, max_iratio)
    except TypeError:
        pass

    df["avg_throughput"] /= 10**9
    df["GRO"] = "GRO " + df["GRO"]

    means_with_int = pd.pivot_table(
        df.loc[(df["INT"] == "enable") & (df["iratio"] <= max_iratio)],
        columns="GRO",
        index="iratio",
        values="avg_throughput",
    )

    fig, ax = plt.subplots(figsize=FIGSIZE, layout="constrained")
    means_with_int.plot(
        ax=ax,
        logx=True,
        marker="s",
        xlabel="tagratio",
        ylabel="Throughput (Gbps)",
    )

    ax.grid(linestyle="--")
    ax.legend(
        bbox_to_anchor=(-0.15, 1.1, 1.15, 0),
        borderaxespad=0,
        loc="lower left",
        mode="expand",
        ncols=df["GRO"].nunique(),
    )

    mid_iratio = df["iratio"].unique()
    mid_iratio = mid_iratio[len(mid_iratio) // 2]
    ax.set_xticks([1, 4, mid_iratio, max_iratio], [1, 4, mid_iratio, "≈ no INT"])

    ax.xaxis.set_minor_locator(ticker.NullLocator())
    ax.yaxis.set_major_locator(ticker.FixedLocator([1, 10, 15, 20, 25, 50, 100]))

    fig.savefig(f"{cca}-iratio-gro-avg_throughput.pdf")

    plt.show()


if __name__ == "__main__":
    raise SystemExit(main())
